# SPDX-License-Identifier: BSD-3-Clause
---
labels:
  - label: "backend"
    matcher:
      changed-files:
        - any-glob-to-any-file: ["core/**", "!core/model/**"]
  - label: "frontend"
    matcher:
      changed-files:
        - any-glob-to-any-file: ["ux/**"]
  - label: "documentation"
    matcher:
      changed-files:
        - any-glob-to-any-file: ["docs/**", "README.md", "CONTRIBUTING.md", "SECURITY.md", "PRIVACY.md"]
  - label: "ci"
    matcher:
      changed-files:
        - any-glob-to-any-file: [".github/**", "!.github/labeler.yml", "Dockerfile", "docker-compose.yml", "flake.nix"]
  - label: "testing"
    matcher:
      changed-files:
        - any-glob-to-any-file: ["tests/**"]
  - label: "ai"
    matcher:
      changed-files:
        - any-glob-to-any-file: ["core/model/**"]
  - label: "dependencies"
    matcher:
      changed-files:
        - any-glob-to-any-file: ["package.json", "package-lock.json", "core/model/requirements.txt"]
  - label: "config"
    matcher:
      changed-files:
        - any-glob-to-any-file:
          - "tsconfig.json"
          - ".eslint*"
          - ".prettierrc"
          - ".yamllint"
          - ".gitignore"
          - "VERSION"
          - ".github/labeler.yml"
