# SPDX-License-Identifier: BSD-3-Clause
---
name: 'Create Release'
description: 'Tags and creates a GitHub release'

runs:
  using: 'composite'
  steps:
    - name: Get version
      run: |
        version="$(cat VERSION)"
        echo "VERSION=${version}" >> "$GITHUB_ENV"
        echo "TAG=${version}" >> "$GITHUB_ENV"
      shell: bash
    - name: Push tag
      run: |
        git tag ${{ env.TAG }}
        git push origin ${{ env.TAG }}
      shell: bash
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG }}
        name: Release ${{ env.TAG }}
        body: Automated release for version ${{ env.TAG }}
        draft: false
        prerelease: false
