# SPDX-License-Identifier: BSD-3-Clause
---
name: 'Git Config'
description: 'Configures git for automated commits'

runs:
  using: 'composite'
  steps:
    - name: Configure git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      shell: bash
